### ISSUE TITLE
doesn't seem to work on arrays

### ISSUE THREAD

**Issue by mimoo** [janestreet/ppx_hash#2]
Hey! It looks like there's no implementation for arrays, anyone knows a work around? I'm getting this error:

```
File "src/lib/pickles_types/plonk_verification_key_evals.ml", line 8, characters 27-32:
8 |       { sigma_comm : 'comm array
                               ^^^^^
Error: Unbound value hash_fold_array
Hint: Did you mean hash_fold_read?
```

**Comment by mimoo** [comment]
adding this in scope made it work: 

```
let hash_fold_array f s x = hash_fold_list f s (Array.to_list x)
```

**Comment by aalekseyev** [comment]
It's missing for arrays deliberately since arrays are mutable, so if you use them as keys in a hashtable it's easy to shoot yourself in the foot by mutating them.

The hashing function for them is provided, under a different name: see [`hash_fold_array_frozen`](https://github.com/janestreet/base/blob/master/src/hash_intf.ml#L95).

I think this function was intended to go with a type definition for frozen arrays, but that was never introduced.
You can use it like this:

```
type 'a my_array = 'a array
let hash_fold_my_array = Base.Hash.Builtin.hash_fold_array_frozen
type 'comm t = {
    sigma_comm : 'comm my_array
} [@@deriving hash]
```
